### ISSUE TITLE
3D platformer error due to whitespace in script

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-demo-projects#360] opened 2019-10-19 13:42 UTC
In Godot 3.2, the 3D platformer demo doesn't run because of whitespace in one of the scripts.

**Comment by hbina** [comment] 2019-11-01 01:19
Oh so this is why it was broken. I thought I did something awful in my fork. Any idea which script is causing it?

**Comment by Calinou** [comment] 2019-11-01 16:00
@hbina I think this is because one of the scripts mixes tabs and spaces for indentation. As of Godot 3.2, you should use either tabs (recommended) or spaces, not both.

**Comment by bojidar-bg** [comment] 2019-11-01 23:19
It should be working with https://github.com/godotengine/godot/pull/32808, can someone confirm?

**Comment by Calinou** [comment] 2020-01-10 22:31
I can't reproduce this on commit https://github.com/godotengine/godot/commit/9600fd5dde1f85b7dd2dd8558d52ff86b18651e7. I'll assume this was fixed by the pull request linked above.

**Closed by Calinou** 2020-01-10 22:31 UTC
Labels: bug
