### ISSUE TITLE
gui_in_3d black viewPort when children are editable

### ISSUE THREAD

**Issue by Hirutenshi** [godotengine/godot-demo-projects#542] opened 2020-10-20 13:06 UTC
Which demo project is affected:
gui_in_3d

OS/device including version:
Windows / 3.2.3.stable.mono.official

Issue description:

- If the GUIPanel3D node is made local or Editable Children is set to true the viewPort will be black when running the project.

- Upon saving the project it also shows "Node not found: Viewport. ViewportTexture: Path to node is invalid"

**Comment by Calinou** [comment] 2020-10-20 13:43
> Upon saving the project it also shows "Node not found: Viewport. ViewportTexture: Path to node is invalid"

This is a known engine bug, see https://github.com/godotengine/godot/issues/27790.

**Comment by Hirutenshi** [comment] 2020-10-20 14:08
Ty for the very fast response!
After reading the engine bug issue I tested some more and was able to make it show the texture. Still getting the error but the UI is visible now.
After "Make Local" I had to reset the nodePath (on the ViewPort Texture) to the viewPort. Still not sure how to change the gui_panel_3d to not throw warnings.

**Comment by aaronfranke** [comment] 2020-11-16 09:12
@Hirutenshi If you think there is a way to work around the engine bug in the demo, that would be great. Otherwise, I think we can just close this issue since it's not a bug with the demo, but a bug with the engine.

**Closed** 2020-11-16 10:05 UTC
