### ISSUE TITLE
Editor quit without helpful error message

### ISSUE THREAD

**Issue by neoedmund** [godotengine/godot-demo-projects#896] opened 2023-03-28 01:59 UTC
**Which demo project is affected:**

instancing.zip

**OS/device including version:**

Linux debian 11
Godot Engine v4.0.1.stable.official.cacf49999 - https://godotengine.org
libspeechd.so.2: cannot open shared object file: No such file or directory
Vulkan API 1.3.238 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 6800 (RADV NAVI21)
or
OpenGL API 4.6 (Core Profile) Mesa 23.0.0 - Compatibility - Using Device: AMD - AMD Radeon RX 6800 (navi21, LLVM 11.0.1, DRM 3.49, 6.2.8-gs)

**Issue description:**

When following the godot-docs-html-master/getting_started/step_by_step/instancing.html
import instancing/project.godot
click `run` , it runs but quit immediately without message.
though I view the script and found `export (PackedScene) var Ball` is wrong, maybe because it's not for v4.0
`SCRIPT ERROR: Parse Error: Unexpected "Identifier" in class body.
          at: GDScript::reload (res://Main.gd:3)`
so I change it to `var Ball`
But still not run. the output is just 2 lines:
```
--- Debugging process started ---
--- Debugging process stopped ---
```
sometimes,  the editor quit without message. I don't know what's the problem.

**Screenshots of issue:**

**Comment by Calinou** [comment] 2023-03-28 02:09
>  though I view the script and found export (PackedScene) var Ball is wrong, maybe because it's not for v4.0

This is indeed the case; the demo is outdated and should be moved to the godot-demo-projects repository. We should stop relying on the ZIP file in the documentation.

Duplicate of https://github.com/godotengine/godot-docs/issues/6793.

**Closed by Calinou** 2023-03-28 02:09 UTC
Labels: bug

**Comment by neoedmund** [comment] 2023-03-28 09:34
Wait, so running an outdated project can result quitting without message? how does Godot judge it's outdated?

**Comment by neoedmund** [comment] 2023-03-28 23:14
That's not the problem! I don't want to complain but what you said is misguiding.
I did another try to use `gdb godot`
I found gdb is not installed, then I installed libboost(needed by gdb) and gdb
then Godot begin to work.
even the said outdated instance.zip runs normally.
I guess some missing `.so` library cause the quiet quitting problem.
`ldd` not show many dependency but in `/proc/xxxx/map` Godot actually used a lot of .so, 
**Godot may fail to work quietly if they are not installed in the system**, they are for instance:
```
/lib/x86_64-linux-gnu/ld-2.31.so
/lib/x86_64-linux-gnu/libc-2.31.so
/lib/x86_64-linux-gnu/libcom_err.so.2.1
/lib/x86_64-linux-gnu/libdbus-1.so.3.19.15
/lib/x86_64-linux-gnu/libdl-2.31.so
/lib/x86_64-linux-gnu/libexpat.so.1.6.12
/lib/x86_64-linux-gnu/libgcc_s.so.1
/lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
/lib/x86_64-linux-gnu/libkeyutils.so.1.9
/lib/x86_64-linux-gnu/liblzma.so.5.2.5
/lib/x86_64-linux-gnu/libm-2.31.so
/lib/x86_64-linux-gnu/libnss_files-2.31.so
/lib/x86_64-linux-gnu/libpthread-2.31.so
/lib/x86_64-linux-gnu/libresolv-2.31.so
/lib/x86_64-linux-gnu/librt-2.31.so
/lib/x86_64-linux-gnu/libtinfo.so.6.2
/lib/x86_64-linux-gnu/libtirpc.so.3.0.0
/lib/x86_64-linux-gnu/libz.so.1.2.11
/opt/vulkansdk/1.3.239.0/x86_64/lib/libvulkan.so.1.3.239
/usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1
/usr/lib/x86_64-linux-gnu/libVkLayer_MESA_device_select.so
/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
/usr/lib/x86_64-linux-gnu/libX11.so.6.4.0
/usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
/usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
/usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
/usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
/usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
/usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
/usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
/usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
/usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
/usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
/usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
/usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1.0.9
/usr/lib/x86_64-linux-gnu/libbrotlidec.so.1.0.9
/usr/lib/x86_64-linux-gnu/libbsd.so.0.11.3
/usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
/usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
/usr/lib/x86_64-linux-gnu/libedit.so.2.0.63
/usr/lib/x86_64-linux-gnu/libelf-0.183.so
/usr/lib/x86_64-linux-gnu/libffi.so.7.1.0
/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.12.0
/usr/lib/x86_64-linux-gnu/libfreetype.so.6.17.4
/usr/lib/x86_64-linux-gnu/libgcrypt.so.20.2.8
/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
/usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
/usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
/usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
/usr/lib/x86_64-linux-gnu/liblz4.so.1.9.3
/usr/lib/x86_64-linux-gnu/libmd.so.0.0.4
/usr/lib/x86_64-linux-gnu/libnsl.so.2.0.1
/usr/lib/x86_64-linux-gnu/libogg.so.0.8.4
/usr/lib/x86_64-linux-gnu/libopus.so.0.8.0
/usr/lib/x86_64-linux-gnu/libpng16.so.16.37.0
/usr/lib/x86_64-linux-gnu/libpulse.so.0.23.0
/usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.31
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
/usr/lib/x86_64-linux-gnu/libsystemd.so.0.30.0
/usr/lib/x86_64-linux-gnu/libudev.so.1.7.0
/usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0
/usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.9
/usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.12
/usr/lib/x86_64-linux-gnu/libvulkan_intel.so
/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
/usr/lib/x86_64-linux-gnu/libwayland-client.so.0.3.0
/usr/lib/x86_64-linux-gnu/libwrap.so.0.7.6
/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
/usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
/usr/lib/x86_64-linux-gnu/libxcb-randr.so.0.1.0
/usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
/usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
/usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0
/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
/usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
/usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
/usr/lib/x86_64-linux-gnu/libz3.so.4
/usr/lib/x86_64-linux-gnu/libzstd.so.1.4.8
/usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-14.2.so
/usr/local/lib/x86_64-linux-gnu/libvulkan_radeon.so
```
