### ISSUE TITLE
Nonexistent function in Platformer 2D demo

### ISSUE THREAD

**Issue by dodosiz** [godotengine/godot-demo-projects#37] opened 2017-02-26 00:55 UTC
I imported the 2D demo project of Platformer and while running the main scene, the debugger dropped the error "Invalid call. Nonexistent function 'move_and_slide' in base 'KinematicBody2D (player.gd)'." for player.gd line 37

**Comment by williamd1k0** [comment] 2017-02-26 04:07
Duplicate of #21 ?

**Comment by akien-mga** [comment] 2017-02-26 09:26
Indeed.

Try the 2.1 branch for 2.1-stable: https://github.com/godotengine/godot-demo-projects/tree/2.1

**Closed by akien-mga** 2017-02-26 09:26 UTC

**Comment by dodosiz** [comment] 2017-02-26 13:16
Oh yes I see.


________________________________
Από: William Tumeo <notifications@github.com>
Στάλθηκε: Κυριακή, 26 Φεβρουαρίου 2017 6:07 πμ
Προς: godotengine/godot-demo-projects
Κοιν.: Theodosis Asvestopoulos; Author
Θέμα: Re: [godotengine/godot-demo-projects] Nonexistent function in Platformer 2D demo (#37)


Duplicate of #21<https://github.com/godotengine/godot-demo-projects/issues/21> ?

**Comment by dodosiz** [comment] 2017-02-26 13:17
Thank you, it worked!


________________________________
Από: Rémi Verschelde <notifications@github.com>
Στάλθηκε: Κυριακή, 26 Φεβρουαρίου 2017 11:26 πμ
Προς: godotengine/godot-demo-projects
Κοιν.: Theodosis Asvestopoulos; Author
Θέμα: Re: [godotengine/godot-demo-projects] Nonexistent function in Platformer 2D demo (#37)


Indeed.

Try the 2.1 branch for 2.1-stable: https://github.com/godotengine/godot-demo-projects/tree/2.1
