### ISSUE TITLE
Examples on the godot-demo-projects Web page (linked from README.md) do not work

### ISSUE THREAD

**Issue by thomasfredericks** [godotengine/godot-demo-projects#917] opened 2023-05-05 12:53 UTC
**The following project do not work:**
* https://godotengine.github.io/godot-demo-projects/2d/bullet_shower/
* https://godotengine.github.io/godot-demo-projects/2d/dodge_the_creeps/
* https://godotengine.github.io/godot-demo-projects/2d/finite_state_machine/
 
Most of the projects do not work... here is an exception that does work : https://godotengine.github.io/godot-demo-projects/gui/drag_and_drop/

**OS/device including version:**
Tested on Windows 11 with Chrome and Firefox

**Issue description:**
When loading the project's Web page, it displays the following error message : `null function or function signature mismatch`

**Screenshots of issue:**
![image](https://user-images.githubusercontent.com/2685516/236461944-05535def-5dd7-400a-82c0-bceb1cb7660b.png)

**Comment by Calinou** [comment] 2023-05-05 13:59
- Duplicate of https://github.com/godotengine/godot-demo-projects/issues/786.

**Closed by Calinou** 2023-05-05 13:59 UTC
Labels: bug
