### ISSUE TITLE
shaders not working 

### ISSUE THREAD

**Issue by Elmapul** [godotengine/godot-demo-projects#197] opened 2018-01-16 10:53 UTC
Godot 3 rc1.
Ubuntu 14.04
Intel® Core™ i5-3317U CPU @ 1.70GHz × 4
Intel® Ivybridge Mobile 
64-bit
------------------------
Runing the material tester,  every material is black instead, running from the terminal i got this output:

ERROR: _display_error_with_code: SceneShaderGLES3: Program LINK FAILED:
FS compile failed: bad cond code

   At: drivers/gles3/shader_gles3.cpp:168.
ERROR: get_current_version: SceneShaderGLES3: Program LINK FAILED:
FS compile failed: bad cond code

   At: drivers/gles3/shader_gles3.cpp:509.
ERROR: get_current_version: Method/Function Failed, returning: __null
   At: drivers/gles3/shader_gles3.cpp:516.
ERROR: bind: Condition ' !version ' is true. returned: false
   At: drivers/gles3/shader_gles3.cpp:123.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:377.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:377.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:377.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:377.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:377.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:377.
boreal@boreal:~/Downloads/Instaladores/Godot/Godot_v3.0-rc1_x11.64/export$

**Comment by akien-mga** [comment] 2018-01-16 12:19
Note that this would be an issue with the engine itself and not the demos, so you should report it on https://github.com/godotengine/godot

But in this case I'm not sure it's worth making a bug report, as the problem is very likely that your system is too old, or more specifically that your Mesa OpenGL drivers for Intel HD 4000 are too old. Ubuntu 14.04 comes with Mesa 10.1 which had only basic support for OpenGL 3.3 - if you update to one of the recent Mesa 17.x releases, you should have OpenGL 4.5 support IIRC, and much better overall support.

To do so, the easiest would likely be for you to upgrade to Ubuntu 16.04. I don't see any decent PPA still providing Mesa builds for 14.04, it's just too old by now.

**Comment by Elmapul** [comment] 2018-01-17 02:40
i see, i didnt installed ubuntu 16.04 because it couldnt even boot here, so since 14.04 was an lts i decided to keep it.
now i have tons of things installed /configured it would be a mess to install another system right now.
i guess i will just stick with gd2 until i can upgrade, even if i do upgrade there is no guarantee that this hardware support glES 3.0

**Comment by akien-mga** [comment] 2018-01-17 07:43
> even if i do upgrade there is no guarantee that this hardware support glES 3.0

It should, AFAIK you have Intel HD 4000 graphics, [which can support OpenGL 4.5](https://www.phoronix.com/scan.php?page=news_item&px=Mesa-17.0-Gets-Haswell-GL45) in the latest Mesa versions. That's what I have (next to a discrete Nvidia GPU) and it works alright.
Godot 3.0 performs relatively badly on such hardware though (low FPS in 3D), so you might indeed want to wait for Godot 3.1 and its GLES 2.0 renderer to have a better workflow.

At any rate, since it's a hardware/drivers issue there's not much we can do to fix it, so closing.

**Closed by akien-mga** 2018-01-17 07:43 UTC
