### ISSUE TITLE
IK Project don't work

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot-demo-projects#396] opened 2020-02-02 08:08 UTC
**Which demo project is affected:**
[3D Ik demo ](https://github.com/godotengine/godot-demo-projects/tree/master/3d/ik), downloaded in 02/02/2020.

**OS/device including version:**
Windows 10 64bits Pro

**Issue description:**
Warning message at project opening in Godot, about `plugin_main.gd.`
Infinite error messages in console.
The Project doesn't launch.

**Screenshots of issue:**

![warning_ik](https://user-images.githubusercontent.com/46683101/73605158-0a1ad700-459b-11ea-9c75-84ebfc566f36.jpg)

![infinites_error](https://user-images.githubusercontent.com/46683101/73605183-4f3f0900-459b-11ea-9d49-1a058cd86a28.jpg)

![crash](https://user-images.githubusercontent.com/46683101/73605194-7a295d00-459b-11ea-86de-9cba5ef0b496.jpg)

**Comment by aaronfranke** [comment] 2020-02-02 08:12
Duplicate of #375

**Closed by aaronfranke** 2020-02-02 08:12 UTC
