### ISSUE TITLE
Web Demos Not Working (indirect call to null)

### ISSUE THREAD

**Issue by popcar2** [godotengine/godot-demo-projects#901] opened 2023-03-30 17:31 UTC
**Which demo project is affected:** Most of them

**OS/device including version:** Windows 10, Firefox 111.0.1

**Issue description:** The official website linked in the Readme for web builds ( https://godotengine.github.io/godot-demo-projects/)  doesn't seem to be working. Thumbnails are missing from most projects, and upon running one of them I get the message "indirect call to null". 

**Screenshots of issue:**
![Image of a web project saying "indirect call to null"](https://user-images.githubusercontent.com/16920817/228916610-a016a858-23bc-4289-8d0b-e75794477f64.png)
![Image of main website with missing thumbnails and empty projects](https://user-images.githubusercontent.com/16920817/228917395-85a5bb92-3bb3-4c19-a3ea-bec75798db48.png)

**Comment by Calinou** [comment] 2023-03-30 19:24
- Duplicate of https://github.com/godotengine/godot-demo-projects/issues/786.

**Closed by Calinou** 2023-03-30 19:24 UTC
Labels: bug
