### ISSUE TITLE
Isometric 2D collision polygons offset

### ISSUE THREAD

**Issue by alexdawn** [godotengine/godot-demo-projects#620] opened 2021-05-22 17:11 UTC
**Which demo project is affected:**
Isometric 2D Demo

**OS/device including version:**
Windows and Linux

**Issue description:**
Browsing the tutorial to work out what is going on, the collision polygons and the sprite don't seem to align right, but the demo performs fine, it seems like just the polygon preview in the tileset resource editor is showing wrong (screenshot below) all the objects Wall, Door and Pillar all are affected.

Why the offset and how would you be able to correctly draw collisions for new sprites?

**Screenshots of issue:**
![image](https://user-images.githubusercontent.com/12990914/119235118-cd287a00-bb28-11eb-9c1a-65e1bca596f7.png)

**Comment by aaronfranke** [comment] 2021-05-22 17:56
@groud Do you know what's going on here? It's possibly a Godot bug. The collisions work fine in-game, but are wrong in the TileSet editor.

**Comment by groud** [comment] 2021-05-23 11:35
Yep, it's a Godot 3.x issue: https://github.com/godotengine/godot/issues/32901

**Comment by aaronfranke** [comment] 2021-05-23 15:54
Alright, so it's not a bug with the demo project. I'll close this issue then. @alexdawn See the linked issue for more information.

**Closed by aaronfranke** 2021-05-23 15:54 UTC
Labels: bug
