### ISSUE TITLE
GUI in 3D: When the viewport uses the `2d` or `viewport` stretch mode, the 3D GUI mouse coordinates are broken

### ISSUE THREAD

**Issue by RedHeadphone** [godotengine/godot-demo-projects#515] opened 2020-08-28 16:43 UTC
when I make the screen on stretch the mouse doesn't take exact position to 3d gui.
It even happens when game is on full screen mode and viewport height and width is not same as displaying screen.

**So maybe the mouse input is based on pixel and not window which is not I want**

Any Solution will helpful . Thanks in advance.

**Comment by QbieShay** [comment] 2020-08-28 19:57
Hello @RedHeadphone , are you referring to a demo project? Or is this a bug that you are experiencing in your own project?

**Comment by Calinou** [comment] 2020-08-29 00:04
This is likely caused by https://github.com/godotengine/godot/issues/34805. See the workarounds described in that issue, which we can apply to this demo.

**Comment by RedHeadphone** [comment] 2020-08-29 12:03
@QbieShay In my own project

**Comment by QbieShay** [comment] 2020-08-29 14:44
@RedHeadphone I will close this issue as a duplicate of [godotengine/godot#34805](https://github.com/godotengine/godot/issues/34805)

This repository is for reporting issues related to the Godot demo projects. If you find other bugs in the engine, please report them [here](https://github.com/godotengine/godot/issues).

**Closed by QbieShay** 2020-08-29 14:44 UTC
Labels: bug
