### ISSUE TITLE
Bug at KinematicCharacter's Cubio.gd

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot-demo-projects#462] opened 2020-04-08 17:56 UTC
**Which demo project is affected:**

https://github.com/godotengine/godot-demo-projects/blob/master/3d/kinematic_character/cubio.gd

**OS/device including version:**
Godot 3.2 Mono - ubuntu 19.10

**Issue description:**

I was wondering @aaronfranke  this code was tested? I've tested it using C# and character walks without pressing any key.

I've converted it to C# resulting on this:
```
		Transform cam_form = GetViewport().GetCamera().GlobalTransform;
		dir = Vector3.Zero;
		dir.x = Input.GetActionStrength("cmd_right") - Input.GetActionStrength("cmd_left");
		dir.z = Input.GetActionStrength("cmd_down") - Input.GetActionStrength("cmd_up");
		
		Basis cam_basis = GetViewport().GetCamera().GlobalTransform.basis;
		Transform basis = cam_form.Rotated(cam_basis.x, -cam_basis.GetEuler().x);
		dir = basis.Xform(dir);
		
		// Limit the input to a length of 1. length_squared is faster to check.
		if (dir.LengthSquared() > 1)
			dir /= dir.Length();

		
		velocity.y += delta * gravity;

		// Using only the horizontal velocity, interpolate towards the input.
		Vector3 hvel = velocity;
		hvel.y = 0f;

		Vector3 target = dir * max_speed;
		float acceleration;
		if (dir.Dot(hvel) > 0)
			acceleration = 2;
		else
			acceleration = 4;

		hvel = hvel.LinearInterpolate(target, acceleration * delta);

		// Assign hvel's values back to velocity, and then move.
		velocity.x = hvel.x;
		velocity.z = hvel.z;
		velocity = MoveAndSlide(velocity, Vector3.Up);

		// Jumping code. is_on_floor() must come after move_and_slide().
		if (IsOnFloor() && Input.IsActionJustPressed("cmd_jump"))
			velocity.y = 7;
```

**Comment by aaronfranke** [comment] 2020-04-08 18:38
Well, yes, the code works and is tested. You can just run the original project to test this.

Your conversion of this code to C# is not a bug with the demo projects, closing.

**Closed by aaronfranke** 2020-04-08 18:38 UTC
Labels: bug
