### ISSUE TITLE
ConvexPolygonShape3D demo project won't run

### ISSUE THREAD

**Issue by Gillissie** [godotengine/godot-demo-projects#952] opened 2023-09-19 05:51 UTC
I'm brand new to Godot and learning, so I don't know how to deal with a demo project that doesn't run, and don't know how to search for existing issues.

**Which demo project is affected:**
https://godotengine.org/asset-library/asset/675

**OS/device including version:**
MacOS Venura 13.1, MacBookPro M1 Max

**Issue description:**
I followed the "online tutorials" link from the help document for ConvexPolygonShape3D. Downloaded the project files, loaded it up, and tried to run it.

**Screenshots of issue:**
![Screenshot 2023-09-19 at 12 47 11 AM](https://github.com/godotengine/godot-demo-projects/assets/645003/7bed7296-c74b-47f7-809b-a4807766a41c)

**Comment by aaronfranke** [comment] 2023-09-19 05:57
The demos haven't all been ported to Godot 4 yet. The copies on the asset library are designed for Godot 3.5.x, but you are using Godot 4.1.1. More volunteers are needed to help port the demos to Godot 4.x. Closing as duplicate of #697.

**Closed by aaronfranke** 2023-09-19 05:57 UTC
Labels: bug
