### ISSUE TITLE
Multiplayer Bomber Demo client crashes after 90 seconds

### ISSUE THREAD

**Issue by Melech** [godotengine/godot-demo-projects#247] opened 2018-04-23 16:25 UTC
When I run this demo, it works fine for exactly 90 seconds, then the non-host client crashes with no error printed in output, or the cmd prompt running in the background.

The host sees the client disconnect after about 5 seconds seconds and ends the game, but never crashes.  Only the clients connecting to the host crash (every time after exactly 90 seconds)

The client thread locks up and becomes unresponsive. Even after I close the non-responsive window, godot still shows the game as running and I have to click stop.

The client crashes even if I do not start the game.  It happens 90 seconds after the UDP(?) connection is established with the server.

I am running this on Godot 3.0.2, windows x64

**Comment by ElefanteNoi** [comment] 2019-07-01 10:44
Still happend in 3.1.1 got socket error: 10054 

[related to this reddit thread](https://www.reddit.com/r/godot/comments/bwifvx/godot_crashes_on_play_errors_out_and_stop/)

**Comment by Calinou** [comment] 2019-07-01 13:17
I can't reproduce this on commit https://github.com/godotengine/godot/commit/6b30f284a0544972f761be3e92ad8d1b176c9f9f on Linux. Maybe this is OS-specific?

**Comment by ElefanteNoi** [comment] 2019-07-03 22:32
After test again on new project with only Node2D the crash is unrelated to Multiplayer Bomber Demo. Crash will always happen to demo that run after the first one.

**Comment by ElefanteNoi** [comment] 2019-07-04 09:09
Found the work around for my problem. 

Wait until second demo stop responding and click X button then
> Try to restore the program

After that join localhost server no longer crash.

**Comment by aaronfranke** [comment] 2020-03-06 01:59
Can anyone confirm if this still happens in Godot 3.2 with the current version of the demo project?

**Comment by ElefanteNoi** [comment] 2020-03-06 02:56
Don't crash anymore for me.

Godot 3.2 with new bomber demo.

**Comment by aaronfranke** [comment] 2020-03-06 03:08
I'm closing this then, but feel free to comment if anyone is experiencing crashes still.

**Closed by aaronfranke** 2020-03-06 03:08 UTC
Labels: bug, needs testing
