### ISSUE TITLE
Audio Mic Record not recording

### ISSUE THREAD

**Issue by X52p** [godotengine/godot-demo-projects#485] opened 2020-06-22 17:14 UTC
**Which demo project is affected:**
godot-demo-projects/audio/mic_record/

**OS/device including version:**
Microsoft Windows 10 Home
Version	10.0.18363 Build 18363
using Godot 3.2.1-stable_win64

**Issue description:**
Audio is not being recorded (Not to file and not for playback)
Steps:
- Opening the demo using Godot and running it (F5)
- Pressing the record button
- Saying something into the microphone
- Pressing the stop button
- Pressing the Play button

Unmuting the Record Bus leads to audio being played all the time (as expected) but doesn't change the behavior of recording. (So Godot seems to be recognising the microphone input)

**Comment by smix8** [comment] 2020-07-25 13:51
Can't recreate the bug with both Godot 3.2.1-stable_win64 and in the recent Godot v3.2.3.beta1.official.
Both play the record fine (BUT it is very quiet on my setup) and also the filesave + playback in another audio program works fine.

**Comment by mauricio-fidalgo** [comment] 2020-09-17 08:45
Recreated the bug on 3.2.2.stable on Linux 64. It doesn't seem to reproduce, and the recorded file doesn't seem to contain any data other than the duration of the recording.

**Comment by Calinou** [comment] 2020-09-17 10:01
@mauricio-fidalgo See https://github.com/godotengine/godot/issues/33184.

**Comment by aaronfranke** [comment] 2020-11-16 09:15
Closing in favor of https://github.com/godotengine/godot/issues/33184, since this is an engine bug, not a demo bug.

**Closed by aaronfranke** 2020-11-16 09:15 UTC
Labels: bug, junior job, needs testing, pr welcome
