### ISSUE TITLE
Hexagonal Map Demo Godot crash

### ISSUE THREAD

**Issue by lifelike** [godotengine/godot-demo-projects#249] opened 2018-04-23 20:35 UTC
Godot Engine crashes or hangs terminally if I just open the Hexagonal Map Demo project from the AssetLib and changes the TileMap type to Custom. It is possible that it just gets stuck doing some calculation, but it seems very dead and it did not wake up for as long as I could be bothered to wait.
Not sure if it is a bug in the demo project or engine itself.

3.0.2.stable.custom_build.2ff3b08
Debian 9.3
Intel(R) HD Graphics 400 (Braswell)

**Comment by Calinou** [comment] 2020-01-10 22:40
Can anyone still reproduce this on Godot 3.1.2 or [Godot 3.2 beta5](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-5)?

**Comment by aaronfranke** [comment] 2020-02-18 18:54
I'm going to close this since the hex map demo has been updated a lot since this issue was created. Feel free to comment if you are still experiencing issues with the latest version from the master branch.

**Closed by aaronfranke** 2020-02-18 18:54 UTC
Labels: bug
