### ISSUE TITLE
3D Platformer demo blasts absurdly loud noise on run

### ISSUE THREAD

**Issue by kettle11** [godotengine/godot-demo-projects#207] opened 2018-01-30 07:50 UTC
After the announcement of Godot 3.0 I wanted to check out an example project. The 3D platformer is the first thing I downloaded and ran. I'm wearing headphones and the volume for my pc is set to about 40%. 

The sound that played through my headphones I can only imagine to be maximum volume possible to be output by my headphones. My ears are ringing minutes later. 

This sound plays whenever I play the project. I haven't changed anything in the project, nor have I changed any settings in Godot 3.0. I only downloaded Godot itself minutes ago. The sound plays for a few seconds before it goes away.

**Comment by akien-mga** [comment] 2018-01-30 08:02
Thanks for the report, and sorry about your ears :) I believe that's the same issue as #202 which was fixed by #205, but I guess we forgot to update the version on the Asset Library, will do now.

**Comment by akien-mga** [comment] 2018-01-30 08:06
Can you download the updated version of the demo now, and confirm that the issue is fixed? https://godotengine.org/asset-library/asset/125

**Comment by kettle11** [comment] 2018-01-30 08:17
Thanks for the prompt response! 

I can confirm the issue is fixed in that build. The spatial audio is actually really cool too!

**Comment by akien-mga** [comment] 2018-01-30 08:21
Awesome :)

**Closed by akien-mga** 2018-01-30 08:21 UTC
