### ISSUE TITLE
GUI in 3D demo not working when when Run On Separate Thread is checked

### ISSUE THREAD

**Issue by IvailoBurov** [godotengine/godot-demo-projects#893] opened 2023-03-22 15:47 UTC
**Which demo project is affected:**

https://github.com/godotengine/godot-demo-projects/tree/master/viewport/gui_in_3d

**OS/device including version:**

Windows 10, NVIDIA GeForce RTX 3070

**Issue description:**

When "Run On Separate Thread" project option is checked for Physics 3D a null result is returned at line 128 for get_world_3d().direct_space_state.

**Screenshots of issue:**

![direct_space_state_is_null](https://user-images.githubusercontent.com/63282037/226960042-68908a1a-f32d-47d3-8319-a2df62882a0c.jpg)

**Comment by Calinou** [comment] 2023-03-22 16:22
As per the [description](https://github.com/godotengine/godot/blob/ce90d77a1857e9cee4b7571258d6e917bf4ba268/doc/classes/World3D.xml#L17) of `World3D.direct_space_state`:

> Direct access to the world's physics 3D space state. Used for querying current and potential collisions. **When using multi-threaded physics, access is limited to [method Node._physics_process] in the main thread.**

**Comment by Sauermann** [comment] 2023-10-11 09:37
I believe, that this gets fixed by #925, which rewrites the demo and removes the `find_mouse()` call.

**Comment by Sauermann** [comment] 2024-02-24 17:08
Haven't tested it, but based on the description, I believe, that with #925 merged, this can now be closed.

**Comment by Calinou** [comment] 2024-02-24 17:12
As of 4.2.1, I can confirm the demo works when **Run on Separate Thread** is enabled for both 2D and 3D physics since https://github.com/godotengine/godot-demo-projects/pull/925 was merged.

**Closed by Calinou** 2024-02-24 17:12 UTC
Labels: bug
