### ISSUE TITLE
2.5D Demo with GDScript - Plugin Error

### ISSUE THREAD

**Issue by christopwner** [godotengine/godot-demo-projects#598] opened 2021-03-13 22:09 UTC
Using `Godot Engine v3.2.3.stable.official` on `Ubuntu 20.04.02 LTS`.

On first load of 2.5D Demo with GDScript, receive the following pop-up warning:
> Unable to load addon script from path: 'res://addons/node25d/node25d_plugin.gd' There seems to be an error in the code, please check the syntax.

With the following dump in output:
> scene/resources/texture.cpp:502 - Condition "!f" is true. Returned: ERR_CANT_OPEN
 Failed loading resource: res://.import/node_25d_icon.png-2ad780313818706789bbb15408797db2.stex. Make sure resources have been imported by opening the project in the editor at least once.
 Failed loading resource: res://addons/node25d/icons/node_25d_icon.png. Make sure resources have been imported by opening the project in the editor at least once.
 res://addons/node25d/node25d_plugin.gd:18 - Parse Error: Can't preload resource at path: res://addons/node25d/icons/node_25d_icon.png
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 Cannot open file 'res://.import/mr_mrs_robot.ogg-04d8a930124c76b878f30fed4f47903c.oggstr'.

After closing and re-opening the editor and project, switching back to `DemoScene` will show following err in output:
>  scene/2d/canvas_item.cpp:483 - Condition "!is_inside_tree()" is true. Returned: get_transform()

**Comment by aaronfranke** [comment] 2021-03-14 00:12
This bug is a duplicate of https://github.com/godotengine/godot/issues/36713

It's a problem with Godot, not this demo.

**Closed by aaronfranke** 2021-03-14 00:12 UTC
Labels: bug
